### PR TITLE
Add person

### PR DESCRIPTION
**Pull request by spraded**
### Add person form

- localhost:8080/person/add will allow users to enter a name and a bio
- Once submitted, that information is plugged into localhost:8080/person
- If multiple people are added, they will all be added to the same page (that will be changed)

### Person model and database

- Person is now connected to SQL through Hibernate
- When information is entered into the add person form, it populates in a SQL table

### Validation dependency

- In order to use validation, I added a javax.validation dependency to build.gradle

### Challenges

- I haven't yet figured out where to store user images. It seems like the database probably isn't the place to do that. 
- I'm also thinking about the most effective way to store and access important dates

### CODE REVIEW

**Comment by gvalencia4** [comment]
I was able to add a person like you described.

Do you know what error this is? I doesn't seem to be affecting anything at the moment.

Screenshot 2023-01-29 at 4 02 56 PM

**Review by gvalencia4 — APPROVED** [review]
In terms of the images, I think we will need to choose a CDN before we can worry about that.

**Comment by spraded** [comment]
Found the source of that error message. It popped up on my machine too, but I didn't immediately look into it since it didn't break anything. It was from the "@Nullable" annotation I tried to use. I'm not even using it now, though. I pulled that out and the error message is gone.

**Comment by FadirTorcer** [comment]
Great work, you two!
In terms of the images, when I was looking at the image for the site (in
the header) I had come across solutions for hosting images in a database.
I'll see if I can dig it up to share!

**Comment by spraded** [comment]
Sounds good, thank you!

**Pull request merged**
